right_motor_driver:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: right_motor_wheel
    joint_speed: 0
    motor:
        id: 1
        init: 0
        min: 0
        max: 0
left_motor_driver:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: left_motor_wheel
    joint_speed: 0
    motor:
        id: 2
        init: 0
        min: 0
        max: 0