dynamic :
  # sampling delta y  
  size_N : 3
  # sampling pose_y
  sample_size: 10
  # min y size
  min_y_distance : 0.4
  max_y_distance : 2
  # 최소 x와의 거리
  min_x_obstacle : 0.2
  # 최소 x size
  max_x_width : 0.2

  # delta y size 조정 
  min_delta_y : 0.015
  max_delta_y : 0.2