local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link

  update_frequency: 4.0
  publish_frequency: 4.0
  transform_tolerance: 1  

  static_map: false  
  rolling_window: true
  width: 4
  height: 2
  resolution: 0.05